-- public.states definition

-- Drop table

-- DROP TABLE public.states;

CREATE TABLE public.states (
                               "number" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               "name" varchar NOT NULL,
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               active bool DEFAULT true NOT NULL,
                               created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               "uuid" uuid NOT NULL,
                               CONSTRAINT states_pk PRIMARY KEY (id),
                               CONSTRAINT states_unique UNIQUE (number),
                               CONSTRAINT states_unique_1 UNIQUE (uuid)
);


-- public.vehicles definition

-- Drop table

-- DROP TABLE public.vehicles;

CREATE TABLE public.vehicles (
                                 id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                 "uuid" uuid NOT NULL,
                                 mark varchar NOT NULL,
                                 color varchar NOT NULL,
                                 plate_number varchar NOT NULL,
                                 passager_capacity int8 NOT NULL,
                                 active bool DEFAULT true NOT NULL,
                                 update_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                 CONSTRAINT vehicles_pk PRIMARY KEY (id),
                                 CONSTRAINT vehicles_unique UNIQUE (uuid)
);


-- public.drivers definition

-- Drop table

-- DROP TABLE public.drivers;

CREATE TABLE public.drivers (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                "name" varchar NOT NULL,
                                phone_number varchar(10) NOT NULL,
                                average_review float4 NOT NULL,
                                "uuid" uuid NOT NULL,
                                active bool DEFAULT true NOT NULL,
                                updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                id_state int8 NOT NULL,
                                id_vehicle int8 NOT NULL,
                                CONSTRAINT driver_pk PRIMARY KEY (id),
                                CONSTRAINT driver_unique UNIQUE (uuid),
                                CONSTRAINT drivers_states_fk FOREIGN KEY (id_state) REFERENCES public.states(id),
                                CONSTRAINT drivers_vehicles_fk FOREIGN KEY (id_vehicle) REFERENCES public.vehicles(id) ON DELETE CASCADE ON UPDATE CASCADE
);


-- public.reviews definition

-- Drop table

-- DROP TABLE public.reviews;

CREATE TABLE public.reviews (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                "uuid" uuid NOT NULL,
                                created_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                updated_at timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                id_driver int8 NOT NULL,
                                average float4 NOT NULL,
                                punctuality int4 NOT NULL,
                                safe_driving int4 NOT NULL,
                                friendliness int4 NOT NULL,
                                cleanliness int4 NOT NULL,
                                "comment" varchar NULL,
                                active bool DEFAULT true NOT NULL,
                                CONSTRAINT reviews_pk PRIMARY KEY (id),
                                CONSTRAINT reviews_unique UNIQUE (uuid),
                                CONSTRAINT reviews_unique_3 UNIQUE (id_driver),
                                CONSTRAINT reviews_drivers_fk FOREIGN KEY (id_driver) REFERENCES public.drivers(id)
);